name: 'DbtDatabricksDemo'
version: '1.0.0'
config-version: 2

profile: 'databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  
models:
  DbtDatabricksDemo:
    +materialized: table
    +catalog: test-izagorodniy
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True

vars:
  elementary:
    test_utils:
      custom_test_names: ["dbt_expectations*"] 
    database: test-izagorodniy
    schema: default